### ISSUE TITLE
dotPath

### ISSUE THREAD

**Issue by crazy4groovy** [d10n/drilldown#1]
Cool lib! Thanks. Reminds me of one I wrote for Groovy: https://gist.github.com/crazy4groovy/8461042 
Perhaps some ideas there on alternative syntax with less paren's. [/suggestion]

**Comment by davidworkman9** [comment]
Was going to suggest the same thing! Only problem is properties could have a dot in their name.

```
var foo = {};
foo['foo.bar'] = 'bar';
```

**Comment by d10n** [comment]
I'd consider adding support for dot notation if we can think of a nice API for it that also allows dots as part of a property name.

Going down the same train of thought, if we allow using dot notation, it would be nice to access indexes of arrays with [].

**Comment by davidworkman9** [comment]
One option could be to restrict dots in property names to being accessed with square brackets.

Example:

```
var foo = {
    bar: {
        'dot.in.it': [1,2,3,4,5]
    }
};

dd(foo, 'bar["dot.in.it"][2]').exists;
```

**Comment by crazy4groovy** [comment]
Perhaps `dd(foo, 'bar.dot\.in\.it[2]').exists;`
Or even `dd(foo, 'bar.dot\.in\.it.2').exists;`! Kinda weird though because the `2` could be a key name or an index value..
Could provide an optional "split" char param like `dd(foo, 'bar:dot.in.it[2]', ':').exists;`

**Comment by d10n** [comment]
I'm wary of adding features that would make drilldown's API more complicated and less consistent.
It might be best to leave this to [_.get](https://lodash.com/docs#get) or [nevernull](https://github.com/jasonmcaffee/nn) (which this library's API takes great inspiration from)

Escaping makes things complicated so I'd like to avoid that.
I'm not yet satisfied with the ways I've thought of to provide a shortcut. I am leaning to not adding this as a feature but I want to leave the issue open for more discussion.

I understand that typing the parentheses each time gets a bit tedious, but it looks uniform and in practice I haven't needed to drill far down enough to get annoyed by the parentheses yet.

Below is something of a brain dump.
Mabye dd could take a second argument which splits on dots.

``` JavaScript
var foo = { abc: { def: { ghi: { 'dot.in.it': { xyz: true } } } } };

// current
   foo  .abc   .def   .ghi  ['dot.in.it'] .xyz  // native shorthand
   foo ['abc']['def']['ghi']['dot.in.it']['xyz']  // native longhand
dd(foo)('abc')('def')('ghi')('dot.in.it')('xyz').val  // safe longhand

// maybe
1:        foo   .abc.def.ghi  ['dot.in.it'] .xyz
2:     dd(foo)(,'abc.def.ghi')('dot.in.it')('xyz').val
3:     dd(foo,  'abc.def.ghi')('dot.in.it')('xyz').val
4: dd(foo).skip('abc.def.ghi')('dot.in.it')('xyz').val  // best safe shorthand?

// 2: too easy to miss the comma?
// 3: the only reason to use more ()s is for variables
//    or known property names with dots now
```

The `.skip()` notation would work nicely but "skip" seems like a long function name and I can't decide on a shorter one:
- `.to()`? All short prepositional words seem interchangable
- `.go()`? Not obvious
- `.z()`? Less obvious

Maybe using multiple `.skip()` calls in one dd wouldn't happen frequently so the length doesn't matter.

I need to think more about using square brackets for arrays.

Thoughts?
